import esbuild from "esbuild";
import process from "node:process";
import builtins from "builtin-modules";

const banner =
  "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. See src/main.ts for source. */";

const prod = process.argv[2] === "production";

/** @type {import('esbuild').BuildOptions} */
const context = {
  banner: {
    js: banner
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js"
};

if (prod) {
  await esbuild.build({
    ...context,
    minify: true
  });
} else {
  const ctx = await esbuild.context(context);
  await ctx.watch();
  process.on("SIGINT", async () => {
    await ctx.dispose();
    process.exit(0);
  });
}
